# Generated by Django 5.1.5 on 2025-02-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("sno", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("content", models.TextField()),
            ],
        ),
    ]
