# Generated by Django 5.1.5 on 2025-02-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("sno", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50)),
                ("content", models.CharField(max_length=1000)),
                ("author", models.CharField(max_length=30)),
                ("timeStamp", models.DateTimeField(blank=True)),
            ],
        ),
    ]
