# Generated by Django 5.1.5 on 2025-02-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.CharField(default="", max_length=30),
            preserve_default=False,
        ),
    ]
