# Generated by Django 5.1.5 on 2025-02-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_orders_alter_contact_desc"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="addressline",
            field=models.CharField(default="", max_length=111),
        ),
        migrations.AddField(
            model_name="orders",
            name="phone",
            field=models.IntegerField(default=9999999999),
        ),
    ]
