# Generated by Django 5.1.5 on 2025-02-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_orders_addressline_orders_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderUpadte",
            fields=[
                ("update_id", models.AutoField(primary_key=True, serialize=False)),
                ("order_id", models.IntegerField(default=0)),
                ("update_desc", models.CharField(max_length=5000)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
