# Generated by Django 5.1.5 on 2025-02-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_orderupadte"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="amount",
            field=models.IntegerField(default=0),
        ),
    ]
